mysite/business/urls.py
from django.urls import path
from .views import *
from django.contrib.auth.views import *


app_name = 'business'

urlpatterns = [
    path('about/', about, name='about'),
    path('sell/', sell, name='sell'),
    path('products/', business_reg, name='reg'),
]

mysite/cart/urls.py
from django.urls import path
from .views import *

app_name = 'cart'

urlpatterns = [
    path('your cart/', add_cart, name= 'your_cart'),
    path('cart_items/', cart, name= 'cart_items'),
]

mysite/mysite/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path('admin/', admin.site.urls),
<<<<<<< HEAD
    path('', include('main.urls')),
    #path('search/', include('main.urls')),
    path('', include('user.urls')),
    path('cart/', include('cart.urls')),
    path('business/', include('business.urls')),

    
] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

=======
    path('main/', include('main.urls')),  # Include the URLs from 'main.urls'
    path('main/home/', views.this, name="this"),  # Define the URL pattern for '/main/home/'
    path('main/results/', include('main.urls')),
    path('main/in/', views.sign, name="sign"),   # Define other URL patterns for 'main/'
    path('main/log/', views.login, name="login"),
]
>>>>>>> 0d52fa95d1254c8ab3f36cd5615a0c6a9733004f

mysite/user/urls.py
from django.urls import path 
from .views import *
from django.contrib.auth import views as auth_views
from .forms import LoginForm


app_name = 'user'

urlpatterns = [
    path('signup/', SignUp, name='signup'),
    path('login/', auth_views.LoginView.as_view(authentication_form=LoginForm, template_name='user/login.html'), name='login'),
    path('logout/', Logout_view , name='logout'),
    path('sell/', Sell, name='sell' ),
    path('details/', Sell_details, name='sell_details' ),
]

mysite/business/models.py
from django.db import models
from django.contrib.auth.models import User


class Business(models.Model):
    owner = models.OneToOneField(User, on_delete= models.CASCADE)
    name = models.CharField(max_length=200, unique=True)
    logo = models.ImageField(upload_to='business_images/')
    description = models.TextField(blank=True, null=True)
    location = models.CharField(max_length=200)
    email = models.EmailField(max_length=200, unique=True)
    contacts = models.CharField(max_length=200)
    
    class Meta():
        ordering = ['name']

    def __str__(self):
        return self.name
    

mysite/business/forms.py
from django import forms
from .models import Business

class BusinessForm(forms.ModelForm):
    class Meta:
        model = Business
        fields = "__all__"


    

mysite/business/views.py
from django.shortcuts import render,redirect
from django.contrib.auth.decorators import login_required
from .forms import BusinessForm
from .models import Business

def about(request):
    return render(request, 'bus/about.html' )

@login_required
def sell(request):
    business = Business.objects.all()
    return render(request, 'bus/dash.html', {'business':business} )

@login_required
def business_reg(request):
    if request.method == 'POST':
        form = BusinessForm(request.POST, request.FILES)
        if form.is_valid():
            form.save()
            return redirect('business:sell')
    else:
        form = BusinessForm()
        return render(request, 'bus/bus_reg.html', {'form':form} )

mysite/business/templates/bus/about.html
{% extends 'bus/business_base.html' %}
{% block title%} products {% endblock %}

{% block content %}
<!-- Navbar Start -->
<div class="container-fluid mb-5">
    <div class="row border-top px-xl-5">
        <div class="col-lg-3 d-none d-lg-block">
            <div class="btn shadow-none d-flex align-items-center justify-content-between bg-primary text-white w-100" data-toggle="collapse" href="#navbar-vertical" style="height: 65px; margin-top: -1px; padding: 0 30px;">
        </div>
    </div>
</div>
<!-- Navbar End -->
<!--about us-->
<div class="container-fluid py-5">
<div class="container">
    <div class="row d-flex justify-content-center">
    <div class="col-lg-7 text-center mb-5">
        <h1 class="display-5 mb-4">Welcome to HIVEMIND</h1>
        <p class="font-weight-medium lead">Hivemind is your one-stop shop for connecting with a buzzing hive of businesses! Inspired by the collaborative spirit of a beehive, we bring together a diverse range of vendors under one roof. Whether you're a seasoned seller or a budding entrepreneur, Hivemind provides the perfect platform to showcase your products and reach a wider audience. <br> With its ever-expanding network, Hivemind fosters a collaborative environment where businesses can thrive together. So, join the hive and watch your business bloom!</p>
        <img src="img/hivemind.png" alt="Image" class="img-fluid w-50 mb-3">
    </div>
    </div>
    <!-- Our Team -->
<div class="container">
<div class="row">
    <div class="col-lg-12 text-center">
        <h2 class="section-heading text-uppercase">Our Team</h2>
    </div>
</div>
<div class="row">
    <!-- Team Member 1 -->
    <div class="col-md-2 col-sm-4 col-xs-6">
        <div class="team-member">
            <img class="mx-auto rounded-circle" src="images/Screenshot (54).png" alt="" style="width: 150px; height: 150px; object-fit: cover; border-radius: 50%;">
            <h4>Mayanja Pius</h4>
            <p class="text-muted">Team leader</p>
        </div>
    </div>
    <!-- Team Member 2 -->
    <div class="col-md-2 col-sm-4 col-xs-6">
        <div class="team-member">
            <img class="mx-auto rounded-circle" src="img/Screenshot (55).png" alt="" style="width: 150px; height: 150px; object-fit: cover; border-radius: 50%;">
            <h4>Cindy</h4>
            <p class="text-muted">backend developer</p>
        </div>
    </div>
    <!-- Team Member 3 -->
    <div class="col-md-2 col-sm-4 col-xs-6">
        <div class="team-member">
            <img class="mx-auto rounded-circle" src="img/Screenshot (56).png" alt="" style="width: 150px; height: 150px; object-fit: cover; border-radius: 50%;">
            <h4>timothy</h4>
            <p class="text-muted">Frontend deveolper</p>
        </div>
    </div>
    <!-- Team Member 4 -->
    <div class="col-md-2 col-sm-4 col-xs-6">
        <div class="team-member">
            <img class="mx-auto rounded-circle" src="img/team/member4.jpg" alt="" style="width: 150px; height: 150px; object-fit: cover; border-radius: 50%;">
            <h4>Member Name</h4>
            <p class="text-muted">Role</p>
        </div>
    </div>
    <!-- Team Member 5 -->
    <div class="col-md-2 col-sm-4 col-xs-6">
        <div class="team-member">
            <img class="mx-auto rounded-circle" src="img/team/member5.jpg" alt="" style="width: 150px; height: 150px; object-fit: cover; border-radius: 50%;">
            <h4>Member Name</h4>
            <p class="text-muted">Role</p>
        </div>
    </div>
</div>
</div>

{% endblock %}

mysite/business/templates/bus/bus_reg.html
{% extends 'bus/business_base.html' %}
{% block title%} Business{% endblock %}

{% block content %}
<div class="w-1/2 my-6 mx-auto p-6 bg-gray-300 rounded-xl">
    <h1 class="text-3xl flex justify-center">Register your business to start selling.</h1>
        <form method="post" enctype="multipart/form-data" class="w-1/2 my-2 mx-auto p-6">
            {% csrf_token %}
            <div class="mb-4">
                <label for="id_owner" class="block text-gray-700 font-bold mb-2">Account Owner:</label>
                <select name="owner" id="id_owner" class="shadow appearance-none border rounded w-full py-2 px-3 text-gray-700 leading-tight focus:outline-none focus:shadow-outline">
                     <option value="{{ user.id }}">{{ user.username }}</option>
        
                </select>
            </div>
            <div class="mb-4">
                <label for="id_name" class="block text-gray-700 font-bold mb-2">Business Name:</label>
                <input type="text" name="name" id="id_name" class="shadow appearance-none border rounded w-full py-2 px-3 text-gray-700 leading-tight focus:outline-none focus:shadow-outline">
            </div>
            
            <div class="mb-4">
                <label for="id_logo" class="block text-gray-700 font-bold mb-2">Logo:</label>
                <input type="file" name="logo" id="id_logo" class="shadow appearance-none border rounded w-full py-2 px-3 text-gray-700 leading-tight focus:outline-none focus:shadow-outline">
            </div>
        
            <div class="mb-4">
                <label for="id_description" class="block text-gray-700 font-bold mb-2">Description:</label>
                <textarea name="description" id="id_description" class="shadow appearance-none border rounded w-full py-2 px-3 text-gray-700 leading-tight focus:outline-none focus:shadow-outline"></textarea>
            </div>
            
            <div class="mb-4">
                <label for="id_location" class="block text-gray-700 font-bold mb-2">Location:</label>
                <input type="text" name="location" id="id_location" class="shadow appearance-none border rounded w-full py-2 px-3 text-gray-700 leading-tight focus:outline-none focus:shadow-outline">
            </div>
            
            <div class="mb-4">
                <label for="id_email" class="block text-gray-700 font-bold mb-2">Email:</label>
                <input type="email" name="email" id="id_email" class="shadow appearance-none border rounded w-full py-2 px-3 text-gray-700 leading-tight focus:outline-none focus:shadow-outline">
            </div>
            
            <div class="mb-4">
                <label for="id_contacts" class="block text-gray-700 font-bold mb-2">Contacts:</label>
                <input type="text" name="contacts" id="id_contacts" class="shadow appearance-none border rounded w-full py-2 px-3 text-gray-700 leading-tight focus:outline-none focus:shadow-outline">
            </div>
            <input type="submit" value="Submit" class="bg-blue-500 hover:bg-blue-700 text-white font-bold py-2 px-4 rounded focus:outline-none focus:shadow-outline">
            <a href="{% url 'business:sell' %}" class="mt-4 text-xl text-blue-500 hover:text-blue-700 block">Already registered</a>
        </form>
        
</div>

{% endblock %}

mysite/business/templates/bus/business_base.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>{% block title%}{% endblock %} | Hivemind</title>
    <link href="https://unpkg.com/tailwindcss@^2/dist/tailwind.min.css" rel="stylesheet">
    <link href='https://unpkg.com/boxicons@2.1.4/css/boxicons.min.css' rel='stylesheet'>
</head>
<body class="bg-gradient-to-r from-purple-400 via-pink-400 to-red-300 items-center">
    <nav class="p-6 flex justify-center items-center bg-gradient-to-r from-purple-400 via-pink-400 to-red-300">
        <h1 class="text-4xl">WELCOME TO HIVEMIND BUSINESS</h1>
    </nav>
   
    <div>
        {% block content %}
        {% endblock %}
    </div>
    <footer class="bg-green-100 mt-3 p-4 font-semibold font-mono">
        <div class="flex justify-center space-x-4">
            <a href="">About</a>
            <a href="#">Privacy policy</a>
        </div>
        <div class="flex justify-center space-x-4">
            <p>follow us on</p>
            <a href="#"><svg class="inline-block mb-1" xmlns="http://www.w3.org/2000/svg" width="24" height="24" viewBox="0 0 24 24" style="fill: rgba(0, 0, 0, 1);transform: msFilter;"><path d="M19.633 7.997c.013.175.013.349.013.523 0 5.325-4.053 11.461-11.46 11.461-2.282 0-4.402-.661-6.186-1.809.324.037.636.05.973.05a8.07 8.07 0 0 0 5.001-1.721 4.036 4.036 0 0 1-3.767-2.793c.249.037.499.062.761.062.361 0 .724-.05 1.061-.137a4.027 4.027 0 0 1-3.23-3.953v-.05c.537.299 1.16.486 1.82.511a4.022 4.022 0 0 1-1.796-3.354c0-.748.199-1.434.548-2.032a11.457 11.457 0 0 0 8.306 4.215c-.062-.3-.1-.611-.1-.923a4.026 4.026 0 0 1 4.028-4.028c1.16 0 2.207.486 2.943 1.272a7.957 7.957 0 0 0 2.556-.973 4.02 4.02 0 0 1-1.771 2.22 8.073 8.073 0 0 0 2.319-.624 8.645 8.645 0 0 1-2.019 2.083z"></path></svg> X</a>
            <a href="#"><svg class="inline-block " xmlns="http://www.w3.org/2000/svg" width="24" height="24" viewBox="0 0 24 24" style="fill: rgba(0, 0, 0, 1);transform: msFilter;"><path d="M20.947 8.305a6.53 6.53 0 0 0-.419-2.216 4.61 4.61 0 0 0-2.633-2.633 6.606 6.606 0 0 0-2.186-.42c-.962-.043-1.267-.055-3.709-.055s-2.755 0-3.71.055a6.606 6.606 0 0 0-2.185.42 4.607 4.607 0 0 0-2.633 2.633 6.554 6.554 0 0 0-.419 2.185c-.043.963-.056 1.268-.056 3.71s0 2.754.056 3.71c.015.748.156 1.486.419 2.187a4.61 4.61 0 0 0 2.634 2.632 6.584 6.584 0 0 0 2.185.45c.963.043 1.268.056 3.71.056s2.755 0 3.71-.056a6.59 6.59 0 0 0 2.186-.419 4.615 4.615 0 0 0 2.633-2.633c.263-.7.404-1.438.419-2.187.043-.962.056-1.267.056-3.71-.002-2.442-.002-2.752-.058-3.709zm-8.953 8.297c-2.554 0-4.623-2.069-4.623-4.623s2.069-4.623 4.623-4.623a4.623 4.623 0 0 1 0 9.246zm4.807-8.339a1.077 1.077 0 0 1-1.078-1.078 1.077 1.077 0 1 1 2.155 0c0 .596-.482 1.078-1.077 1.078z"></path><circle cx="11.994" cy="11.979" r="3.003"></circle></svg> Instagram</a>

            <a href="#"><svg class="w-4 inline-block" xmlns="http://www.w3.org/2000/svg" width="24" height="24" viewBox="0 0 24 24" style="fill: rgba(0, 0, 0, 1);transform: msFilter;"><path d="M13.397 20.997v-8.196h2.765l.411-3.209h-3.176V7.548c0-.926.258-1.56 1.587-1.56h1.684V3.127A22.336 22.336 0 0 0 14.201 3c-2.444 0-4.122 1.492-4.122 4.231v2.355H7.332v3.209h2.753v8.202h3.312z"></path></svg> Facebook</a>

            <a href="#"><svg class="w-6 inline-block" xmlns="http://www.w3.org/2000/svg" width="24" height="24" viewBox="0 0 24 24" style="fill: rgba(0, 0, 0, 1);transform:msFilter;"><path d="M21.593 7.203a2.506 2.506 0 0 0-1.762-1.766C18.265 5.007 12 5 12 5s-6.264-.007-7.831.404a2.56 2.56 0 0 0-1.766 1.778c-.413 1.566-.417 4.814-.417 4.814s-.004 3.264.406 4.814c.23.857.905 1.534 1.763 1.765 1.582.43 7.83.437 7.83.437s6.265.007 7.831-.403a2.515 2.515 0 0 0 1.767-1.763c.414-1.565.417-4.812.417-4.812s.02-3.265-.407-4.831zM9.996 15.005l.005-6 5.207 3.005-5.212 2.995z"></path></svg> YouTube</a>
        </div>
    </footer>
</body>
</html>

mysite/business/templates/bus/dash.html
<!DOCTYPE html>
<html lang="en">
{% load static %}
<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Responsive Admin Dashboard | Korsat X Parmaga</title>
    <!-- ======= Styles ====== -->
    <link rel="stylesheet" href="{% static 'assets/css/style.css' %}">
</head>
<body>
    <!-- =============== Navigation ================ -->
    <div class="container">
        <div class="navigation">
            <ul>
                <li>
                    <a href="#">
                        <span class="icon">
                            <ion-icon name="logo-apple"></ion-icon>
                        </span>
                        {% for busi in business%}
                            {% if busi.owner == request.user %}
                            <span class="title">{{busi.name}}</span>
                            {% endif %}
                        {% endfor %}
                    </a>
                </li>

                <li>
                    <a href="{% url 'jumia:items' %}">
                        <span class="icon">
                            <ion-icon name="home-outline"></ion-icon>
                        </span>
                        <span class="title">Home page</span>
                    </a>
                </li>

                <li>
                    <a href="#">
                        <span class="icon">
                            <ion-icon name="people-outline"></ion-icon>
                        </span>
                        <span class="title">Customers</span>
                    </a>
                </li>

                <li>
                    <a href="#">
                        <span class="icon">
                            <ion-icon name="chatbubble-outline"></ion-icon>
                        </span>
                        <span class="title">Manage Products</span>
                    </a>
                </li>

                <li>
                    <a href="#">
                        <span class="icon">
                            <ion-icon name="help-outline"></ion-icon>
                        </span>
                        <span class="title">Orders</span>
                    </a>
                </li>

                <li>
                    <a href="#">
                        <span class="icon">
                            <ion-icon name="settings-outline"></ion-icon>
                        </span>
                        <span class="title">Settings</span>
                    </a>
                </li>

                <li>
                    <a href="#">
                        <span class="icon">
                            <ion-icon name="lock-closed-outline"></ion-icon>
                        </span>
                        <span class="title">Password</span>
                    </a>
                </li>

                <li>
                    <a href="{% url 'user:logout' %}">
                        <span class="icon">
                            <ion-icon name="log-out-outline"></ion-icon>
                        </span>
                        <span class="title">Log Out</span>
                    </a>
                </li>
            </ul>
        </div>

        <!-- ========================= Main ==================== -->
        <div class="main">
            <div class="topbar">
                <div class="toggle">
                    <ion-icon name="menu-outline"></ion-icon>
                </div>

                <div class="search">
                    <label>
                        <input type="text" placeholder="Search here">
                        <ion-icon name="search-outline"></ion-icon>
                    </label>
                </div>

                <div class="user">
                    <img src="{% static 'assets/imgs/customer01.jpg' %}" alt="">
                </div>
            </div>

            <!-- ======================= Cards ================== -->
            <div class="cardBox">
                <div class="card">
                    <div>
                        <div class="numbers">1,504</div>
                        <div class="cardName">Daily Views</div>
                    </div>

                    <div class="iconBx">
                        <ion-icon name="eye-outline"></ion-icon>
                    </div>
                </div>

                <div class="card">
                    <div>
                        <div class="numbers">80</div>
                        <div class="cardName">Sales</div>
                    </div>

                    <div class="iconBx">
                        <ion-icon name="cart-outline"></ion-icon>
                    </div>
                </div>

                <div class="card">
                    <div>
                        <div class="numbers">284</div>
                        <div class="cardName">Comments</div>
                    </div>

                    <div class="iconBx">
                        <ion-icon name="chatbubbles-outline"></ion-icon>
                    </div>
                </div>

                <div class="card">
                    <div>
                        <div class="numbers">$7,842</div>
                        <div class="cardName">Earning</div>
                    </div>

                    <div class="iconBx">
                        <ion-icon name="cash-outline"></ion-icon>
                    </div>
                </div>
            </div>

            <!-- ================ Order Details List ================= -->
            <div class="details">
                <div class="recentOrders">
                    <div class="cardHeader">
                        <h2>Recent Orders</h2>
                        <a href="#" class="btn">View All</a>
                    </div>

                    <table>
                        <thead>
                            <tr>
                                <td>Name</td>
                                <td>Price</td>
                                <td>Payment</td>
                                <td>Status</td>
                            </tr>
                        </thead>

                        <tbody>
                            <tr>
                                <td>Star Refrigerator</td>
                                <td>$1200</td>
                                <td>Paid</td>
                                <td><span class="status delivered">Delivered</span></td>
                            </tr>

                            <tr>
                                <td>Dell Laptop</td>
                                <td>$110</td>
                                <td>Due</td>
                                <td><span class="status pending">Pending</span></td>
                            </tr>

                            <tr>
                                <td>Apple Watch</td>
                                <td>$1200</td>
                                <td>Paid</td>
                                <td><span class="status return">Return</span></td>
                            </tr>

                            <tr>
                                <td>Addidas Shoes</td>
                                <td>$620</td>
                                <td>Due</td>
                                <td><span class="status inProgress">In Progress</span></td>
                            </tr>

                            <tr>
                                <td>Star Refrigerator</td>
                                <td>$1200</td>
                                <td>Paid</td>
                                <td><span class="status delivered">Delivered</span></td>
                            </tr>

                            <tr>
                                <td>Dell Laptop</td>
                                <td>$110</td>
                                <td>Due</td>
                                <td><span class="status pending">Pending</span></td>
                            </tr>

                            <tr>
                                <td>Apple Watch</td>
                                <td>$1200</td>
                                <td>Paid</td>
                                <td><span class="status return">Return</span></td>
                            </tr>

                            <tr>
                                <td>Addidas Shoes</td>
                                <td>$620</td>
                                <td>Due</td>
                                <td><span class="status inProgress">In Progress</span></td>
                            </tr>
                        </tbody>
                    </table>
                </div>

                <!-- ================= New Customers ================ -->
                <div class="recentCustomers">
                    <div class="cardHeader">
                        <h2>Recent Customers</h2>
                    </div>
                </div>
            </div>
        </div>
    </div>

    <!-- =========== Scripts =========  -->
    <script src="{%static 'assets/js/main.js' %}"></script>

    <!-- ====== ionicons ======= -->
    <script type="module" src="https://unpkg.com/ionicons@5.5.2/dist/ionicons/ionicons.esm.js"></script>
    <script nomodule src="https://unpkg.com/ionicons@5.5.2/dist/ionicons/ionicons.js"></script>
</body>

</html>

mysite/business/templates/bus/login.html
<!DOCTYPE html>
<html lang="en">

<head>
    <meta charset="utf-8">
    <title>HIVEMIND</title>
    <meta content="width=device-width, initial-scale=1.0" name="viewport">
    <!-- Favicon -->
    <link href="img/favicon.ico" rel="icon">

    <!-- Google Web Fonts -->
    <link rel="preconnect" href="https://fonts.gstatic.com">
    <link href="https://fonts.googleapis.com/css2?family=Poppins:wght@100;200;300;400;500;600;700;800;900&display=swap" rel="stylesheet"> 

    <!-- Font Awesome -->
    <link href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/5.10.0/css/all.min.css" rel="stylesheet">

    <!-- Libraries Stylesheet -->
    <link href="lib/owlcarousel/assets/owl.carousel.min.css" rel="stylesheet">

    <!-- Customized Bootstrap Stylesheet -->
    <link href="css/style.css" rel="stylesheet">
</head>
<body>
    <!-- Topbar Start -->
    <div class="container-fluid">
        <div class="row bg-secondary py-2 px-xl-5">
            <div class="col-lg-6 d-none d-lg-block">
                <div class="d-inline-flex align-items-center">
                    <a class="text-dark" href="">FAQs</a>
                    <span class="text-muted px-2">|</span>
                    <a class="text-dark" href="">Help</a>
                    <span class="text-muted px-2">|</span>
                    <a class="text-dark" href="">Support</a>
                </div>
            </div>
            <div class="col-lg-6 text-center text-lg-right">
                <div class="d-inline-flex align-items-center">
                    <a class="text-dark px-2" href="">
                        <i class="fab fa-facebook-f"></i>
                    </a>
                    <a class="text-dark px-2" href="">
                        <i class="fab fa-twitter"></i>
                    </a>
                    <a class="text-dark px-2" href="">
                        <i class="fab fa-linkedin-in"></i>
                    </a>
                    <a class="text-dark px-2" href="">
                        <i class="fab fa-instagram"></i>
                    </a>
                    <a class="text-dark pl-2" href="">
                        <i class="fab fa-youtube"></i>
                    </a>
                </div>
            </div>
        </div>
            
        </div>
    </div><hr>
    <!-- Topbar End -->
    <!--login form start-->
    <div class="container-fluid bg-secondary text-dark pt-3 mb-5">
        <div class="row px-xl-5 pt-5">
          <div class="col-lg-6 mx-auto mb-4">
            <div class="row">
              <div class="col-lg-12">
                <h2 class="font-weight-bold mb-4">Login</h2>
                <form>
                  <div class="form-group">
                    <label for="username">Username or Email</label>
                    <input type="text" class="form-control" id="username" placeholder="Enter Username or Email" required>
                  </div>
                  <div class="form-group">
                    <label for="password">Password</label>
                    <input type="password" class="form-control" id="password" placeholder="Password" required>
                  </div>
                  <div class="form-group form-check">
                    <input type="checkbox" class="form-check-input" id="rememberMe">
                    <label class="form-check-label" for="rememberMe">Remember me</label>
                  </div>
                  <button type="submit" class="btn btn-primary">Login</button>
                  <a href="#" class="btn btn-outline-primary ml-2">Forgot Password?</a>
                </form>
              </div>
            </div>
          </div>
        </div>
      </div>
      <!--login end-->  
    <!-- Footer Start -->
    <div class="container-fluid bg-secondary text-dark mt-5 pt-5" style="margin-top: 50px;">
        <div class="row px-xl-5 pt-5 ">
            <div class="col-lg-4 col-md-12 mb-5 pr-3 pr-xl-5">
                <a href="" class="text-decoration-none">
                    <h1 class="mb-4 display-5 font-weight-semi-bold"><span class="text-primary font-weight-bold border border-white px-3 mr-1">HIVEMIND</span></h1>
                </a>
                <p class="mb-2"><i class="fa fa-map-marker-alt text-primary mr-3"></i>makerere university</p>
                <p class="mb-2"><i class="fa fa-envelope text-primary mr-3"></i>info@hivemind.com</p>
                <p class="mb-0"><i class="fa fa-phone-alt text-primary mr-3"></i>+256</p>
            </div>
            <div class="col">About us
                <li><a href="contact_us.html" target="_blank">About_us</a></li>
                <li><a href="Terms&condition.html" target="_blank">Terms&condition</a></li>     
                <li><a href="refund&return policy.html" target="_blank">refund&return policy</a></li>
            </div>
                    <div class="col-md-4 mb-5">
                        <h5 class="font-weight-bold text-dark mb-4">Newsletter</h5>
                        <form action="">
                            <div class="form-group">
                                <input type="text" class="form-control border-0 py-4" placeholder="Your Name" required="required" />
                            </div>
                            <div class="form-group">
                                <input type="email" class="form-control border-0 py-4" placeholder="Your Email"
                                    required="required" />
                            </div>
                            <div>
                                <button class="btn btn-primary btn-block border-0 py-3" type="submit">Subscribe Now</button>
                            </div>
                        </form>
                    </div>
                </div>
            </div>
        </div>
        <div class="row border-top border-light mx-xl-5 py-4">
            <div class="col-md-6 px-xl-0">
                <p class="mb-md-0 text-center text-md-left text-dark">
                    &copy; <a class="text-dark font-weight-semi-bold" href="#">hivemind</a>  
                </p>
            </div>
            <div class="col-md-6 px-xl-0 text-center text-md-right">
                <img class="img-fluid" src="img/payments.png" alt="">
            </div>
        </div>
    </div>
    <!-- Footer End -->
    <!-- Back to Top -->
    <a href="#" class="btn btn-primary back-to-top"><i class="fa fa-angle-double-up"></i></a>
    <!-- JavaScript Libraries -->
    <script src="https://code.jquery.com/jquery-3.4.1.min.js"></script>
    <script src="https://stackpath.bootstrapcdn.com/bootstrap/4.4.1/js/bootstrap.bundle.min.js"></script>
    <script src="lib/easing/easing.min.js"></script>
    <script src="lib/owlcarousel/owl.carousel.min.js"></script>
    <!-- Contact Javascript File -->
    <script src="mail/jqBootstrapValidation.min.js"></script>
    <script src="mail/contact.js"></script>
    <!-- Template Javascript -->
    <script src="js/main.js"></script>
</body>
</html>

mysite/business/templates/bus/sells.html
{% extends 'bus/business_base.html' %}

{% block title %}Sell{% endblock %}

{% block content %}
<div>
    <p> waguan</p>
</div>

{% endblock %}