mysite/cart/urls.py
from django.urls import path
from .views import *

app_name = 'cart'

urlpatterns = [
    path('your cart/', add_cart, name= 'your_cart'),
    path('cart_items/', cart, name= 'cart_items'),
]

mysite/mysite/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path('admin/', admin.site.urls),
<<<<<<< HEAD
    path('', include('main.urls')),
    #path('search/', include('main.urls')),
    path('', include('user.urls')),
    path('cart/', include('cart.urls')),
    path('business/', include('business.urls')),

    
] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

=======
    path('main/', include('main.urls')),  # Include the URLs from 'main.urls'
    path('main/home/', views.this, name="this"),  # Define the URL pattern for '/main/home/'
    path('main/results/', include('main.urls')),
    path('main/in/', views.sign, name="sign"),   # Define other URL patterns for 'main/'
    path('main/log/', views.login, name="login"),
]
>>>>>>> 0d52fa95d1254c8ab3f36cd5615a0c6a9733004f

mysite/user/urls.py
from django.urls import path 
from .views import *
from django.contrib.auth import views as auth_views
from .forms import LoginForm


app_name = 'user'

urlpatterns = [
    path('signup/', SignUp, name='signup'),
    path('login/', auth_views.LoginView.as_view(authentication_form=LoginForm, template_name='user/login.html'), name='login'),
    path('logout/', Logout_view , name='logout'),
    path('sell/', Sell, name='sell' ),
    path('details/', Sell_details, name='sell_details' ),
]

mysite/user/models.py
from django.db import models

# Create your models here.

mysite/user/forms.py
from django.contrib.auth.models import User
from django.contrib.auth.forms import UserCreationForm, AuthenticationForm
from django import forms
from main.models import Product, Type, Categories

class LoginForm(AuthenticationForm):
    username = forms.CharField(widget=forms.TextInput(attrs={
        'placeholder': 'Your username',
        'class': 'w-full py-4 px-6 rounded-xl'
    }))
    password = forms.CharField(widget=forms.PasswordInput(attrs={
        'placeholder': 'Your password',
        'class': 'w-full py-4 px-6 rounded-xl'
    }))


class SignUpForm(UserCreationForm):
    class Meta:
        model = User
        fields = ('username', 'email', 'password1', 'password2')

    username = forms.CharField(widget=forms.TextInput(attrs={
        'placeholder': 'Your username',
        'class': 'w-full py-4 px-6 rounded-xl'
    }))
    email = forms.CharField(widget=forms.EmailInput(attrs={
        'placeholder': 'Your email address',
        'class': 'w-full py-4 px-6 rounded-xl'
    }))
    password1 = forms.CharField(widget=forms.PasswordInput(attrs={
        'placeholder': 'Your password',
        'class': 'w-full py-4 px-6 rounded-xl'
    }))
    password2 = forms.CharField(widget=forms.PasswordInput(attrs={
        'placeholder': 'Repeat password',
        'class': 'w-full py-4 px-6 rounded-xl'
    }))

class SellForm(forms.ModelForm):
    class Meta:
        model = Product
        fields = "__all__"
    
class design(forms.Select):
    def __init__(self, *args, **kwargs):
        super().__init__(*args, **kwargs)
        self.attrs['class'] = ' form-select w-full py-4 px-6 rounded-xl'

class DetailForm(forms.ModelForm):
    class Meta:
        model = Type
        fields = '__all__'

    Category = forms.ModelChoiceField(queryset=Product.objects.all(), widget=design)

    name = forms.CharField(widget=forms.TextInput(attrs={
        'placeholder': 'Your username',
        'class': 'w-full py-4 px-6 rounded-xl'}))

    description = forms.CharField(widget=forms.Textarea(attrs={
        'placeholder': 'product description',
        'class': 'w-full py-4 px-6 rounded-xl'}))
    

mysite/user/views.py
from django.shortcuts import render,redirect
from .forms import SignUpForm, SellForm, DetailForm
from django.contrib.auth import logout
from django.contrib.auth.decorators import login_required

def SignUp(request):
    if request.method == 'POST':
        form = SignUpForm(request.POST)

        if form.is_valid():
            form.save()

            return redirect('/login/')
    else:
        form = SignUpForm()

    return render(request, 'user/signup.html', {'form':form})


def Logout_view(request):
    logout(request)
    return redirect('/')

@login_required
def Sell(request):
    if request.method == 'POST':
        form = SellForm(request.POST)

        if form.is_valid():
            form.save()

            return redirect('user:sell_details')
    else:
        form = SellForm()

    return render(request, 'user/sell.html', {'form':form})


def Sell_details(request):
    if request.method == 'POST':
        form = DetailForm(request.POST, request.FILES)

        if form.is_valid():
            form.save()

            return redirect('/')
    else:
        form = DetailForm()

    return render(request, 'user/sell_details.html', {'form':form})

mysite/user/templates/user/login.html
{% extends 'user/user_base.html' %}

{% block title %}Login{% endblock %}

{% block content %}
<div class="w-1/2 my-6 mx-auto p-6 bg-gray-300  rounded-xl">
    <h1 class="mb-6 text-4xl text-center">Login</h1>

    <form method="post" action=".">
        {% csrf_token %}

        <div class="mb-3">
            <label class="inline-block mb-2">Username</label><br>
            {{ form.username }}
        </div>

        <div class="mb-3">
            <label class="inline-block mb-2">Password</label><br>
            {{ form.password }}
        </div>

        {% if form.errors or form.non_field_errors %}
            <div class="mb-3 p-6 bg-red-100 rounded-xl">
                {% for field in form %}
                    {{ field.errors }}
                {% endfor %}

                {{ form.non_field_errors }}
            </div>
        {% endif %}
        <br>
       <div class="flex justify-between mb-3">
        <a href="#"><p class="font-semibold text-lg hover hover:text-red-500">Forgot password?</p></a>
        <a href="{% url 'user:signup' %}" class="font-semibold text-lg hover hover:text-red-500">Don't have an account</a>
       </div>
        <button class="py-4 px-8 text-lg bg-green-500 hover:bg-green-700 rounded-xl text-white">Login</button>
    </form>
</div>
{% endblock %}

mysite/user/templates/user/logout.html
{% extends 'user/base.html' %}

{% block title %}Sign up{% endblock %}

{% block content %}
<div class="w-1/2 my-6 mx-auto p-6 bg-gray-100 rounded-xl">
    <h1 class="mb-6 text-3xl">Logged Out Successfully</h1>

    <a href=""><button class="py-4 px-8 text-lg bg-green-500 hover:bg-green-700 rounded-xl text-white">Login</button></a>
</div>
{% endblock %}

mysite/user/templates/user/sell.html
{% extends 'jumia/base.html' %}

{% block title %}Sell{% endblock %}

{% block content %}
<div class="w-1/2 my-6 mx-auto p-6 bg-gray-200  rounded-xl">
    <h1 class="mb-6 text-4xl text-center">Sell a product</h1>

    <form method="post" action=".">
        {% csrf_token %}
        {{form.as_p}}
        
        
        <a href="{% url 'user:sell_details' %}">
            <button class="py-1 px-4 text-lg bg-green-500 hover:bg-green-700 rounded-xl text-white">Next</button>
        </a>
    </form>
</div>
{% endblock %}

mysite/user/templates/user/sell_details.html
{% extends 'jumia/base.html' %}

{% block title %}Sell{% endblock %}

{% block content %}
<div class="w-1/2 my-6 mx-auto p-6 bg-gray-300  rounded-xl">
    <h1 class="mb-6 text-4xl text-center">Product details</h1>

    <form method="post" action="." enctype="multipart/form-data">
        {% csrf_token %}
        {{form.as_p}}
       
        <button class="py-4 px-8 text-lg bg-green-500 hover:bg-green-700 rounded-xl text-white">Sell</button>
    </form>
</div>
{% endblock %}

mysite/user/templates/user/signup.html
{% extends 'user/user_base.html' %}

{% block title %}Sign up{% endblock %}

{% block content %}
<div class="w-1/2 my-6 mx-auto p-6 bg-gray-300 rounded-xl">
    <h1 class="mb-6 text-3xl">Sign up</h1>

    <form method="post" action=".">
        {% csrf_token %}

        <div class="mb-3">
            <label class="inline-block mb-2">Username</label><br>
            {{ form.username }}
        </div>

        <div class="mb-3">
            <label class="inline-block mb-2">Email</label><br>
            {{ form.email }}
        </div>

        <div class="mb-3">
            <label class="inline-block mb-2">Password</label><br>
            {{ form.password1 }}
        </div>

        <div class="mb-3">
            <label class="inline-block mb-2">Repeat password</label><br>
            {{ form.password2 }}
        </div>

        {% if form.errors or form.non_field_errors %}
            <div class="mb-3 p-6 bg-red-100 rounded-xl">
                {% for field in form %}
                    {{ field.errors }}
                {% endfor %}

                {{ form.non_field_errors }}
            </div>
        {% endif %}
        <br>
        <button class="py-4 px-8 text-lg bg-green-500 hover:bg-green-700 rounded-xl text-white">Sign Up</button>
    </form>
</div>
{% endblock %}

mysite/user/templates/user/user_base.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>{% block title%}{% endblock %} | Hivemind</title>
    <link href="https://unpkg.com/tailwindcss@^2/dist/tailwind.min.css" rel="stylesheet">
    <link href='https://unpkg.com/boxicons@2.1.4/css/boxicons.min.css' rel='stylesheet'>
</head>
<body class="bg-gradient-to-r from-purple-400 via-pink-400 to-red-300">
    <nav class="p-6 flex justify-center items-center bg-gradient-to-r from-purple-400 via-pink-400 to-red-300">
        <a href="" class="text-4xl"> WELCOME TO HIVEMIND 
            <svg class= "w-8 inline-block mb-2" xmlns="http://www.w3.org/2000/svg" fill="none" viewBox="0 0 24 24" stroke-width="1.5" stroke="currentColor" class="w-6 h-6">
            <path stroke-linecap="round" stroke-linejoin="round" d="M15.75 10.5V6a3.75 3.75 0 1 0-7.5 0v4.5m11.356-1.993 1.263 12c.07.665-.45 1.243-1.119 1.243H4.25a1.125 1.125 0 0 1-1.12-1.243l1.264-12A1.125 1.125 0 0 1 5.513 7.5h12.974c.576 0 1.059.435 1.119 1.007ZM8.625 10.5a.375.375 0 1 1-.75 0 .375.375 0 0 1 .75 0Zm7.5 0a.375.375 0 1 1-.75 0 .375.375 0 0 1 .75 0Z" />
          </svg>
        </a>
    </nav>
   
    <div>
        {% block content %}
        {% endblock %}
    </div>
    <footer class="bg-green-100 mt-3 p-4 font-semibold font-mono">
        <div class="flex justify-center space-x-4">
            <a href="">About</a>
            <a href="#">Privacy policy</a>
        </div>
        <div class="flex justify-center space-x-4">
            <p>follow us on</p>
            <a href="#"><svg class="inline-block mb-1" xmlns="http://www.w3.org/2000/svg" width="24" height="24" viewBox="0 0 24 24" style="fill: rgba(0, 0, 0, 1);transform: msFilter;"><path d="M19.633 7.997c.013.175.013.349.013.523 0 5.325-4.053 11.461-11.46 11.461-2.282 0-4.402-.661-6.186-1.809.324.037.636.05.973.05a8.07 8.07 0 0 0 5.001-1.721 4.036 4.036 0 0 1-3.767-2.793c.249.037.499.062.761.062.361 0 .724-.05 1.061-.137a4.027 4.027 0 0 1-3.23-3.953v-.05c.537.299 1.16.486 1.82.511a4.022 4.022 0 0 1-1.796-3.354c0-.748.199-1.434.548-2.032a11.457 11.457 0 0 0 8.306 4.215c-.062-.3-.1-.611-.1-.923a4.026 4.026 0 0 1 4.028-4.028c1.16 0 2.207.486 2.943 1.272a7.957 7.957 0 0 0 2.556-.973 4.02 4.02 0 0 1-1.771 2.22 8.073 8.073 0 0 0 2.319-.624 8.645 8.645 0 0 1-2.019 2.083z"></path></svg> X</a>
            <a href="#"><svg class="inline-block " xmlns="http://www.w3.org/2000/svg" width="24" height="24" viewBox="0 0 24 24" style="fill: rgba(0, 0, 0, 1);transform: msFilter;"><path d="M20.947 8.305a6.53 6.53 0 0 0-.419-2.216 4.61 4.61 0 0 0-2.633-2.633 6.606 6.606 0 0 0-2.186-.42c-.962-.043-1.267-.055-3.709-.055s-2.755 0-3.71.055a6.606 6.606 0 0 0-2.185.42 4.607 4.607 0 0 0-2.633 2.633 6.554 6.554 0 0 0-.419 2.185c-.043.963-.056 1.268-.056 3.71s0 2.754.056 3.71c.015.748.156 1.486.419 2.187a4.61 4.61 0 0 0 2.634 2.632 6.584 6.584 0 0 0 2.185.45c.963.043 1.268.056 3.71.056s2.755 0 3.71-.056a6.59 6.59 0 0 0 2.186-.419 4.615 4.615 0 0 0 2.633-2.633c.263-.7.404-1.438.419-2.187.043-.962.056-1.267.056-3.71-.002-2.442-.002-2.752-.058-3.709zm-8.953 8.297c-2.554 0-4.623-2.069-4.623-4.623s2.069-4.623 4.623-4.623a4.623 4.623 0 0 1 0 9.246zm4.807-8.339a1.077 1.077 0 0 1-1.078-1.078 1.077 1.077 0 1 1 2.155 0c0 .596-.482 1.078-1.077 1.078z"></path><circle cx="11.994" cy="11.979" r="3.003"></circle></svg> Instagram</a>

            <a href="#"><svg class="w-4 inline-block" xmlns="http://www.w3.org/2000/svg" width="24" height="24" viewBox="0 0 24 24" style="fill: rgba(0, 0, 0, 1);transform: msFilter;"><path d="M13.397 20.997v-8.196h2.765l.411-3.209h-3.176V7.548c0-.926.258-1.56 1.587-1.56h1.684V3.127A22.336 22.336 0 0 0 14.201 3c-2.444 0-4.122 1.492-4.122 4.231v2.355H7.332v3.209h2.753v8.202h3.312z"></path></svg> Facebook</a>

            <a href="#"><svg class="w-6 inline-block" xmlns="http://www.w3.org/2000/svg" width="24" height="24" viewBox="0 0 24 24" style="fill: rgba(0, 0, 0, 1);transform:msFilter;"><path d="M21.593 7.203a2.506 2.506 0 0 0-1.762-1.766C18.265 5.007 12 5 12 5s-6.264-.007-7.831.404a2.56 2.56 0 0 0-1.766 1.778c-.413 1.566-.417 4.814-.417 4.814s-.004 3.264.406 4.814c.23.857.905 1.534 1.763 1.765 1.582.43 7.83.437 7.83.437s6.265.007 7.831-.403a2.515 2.515 0 0 0 1.767-1.763c.414-1.565.417-4.812.417-4.812s.02-3.265-.407-4.831zM9.996 15.005l.005-6 5.207 3.005-5.212 2.995z"></path></svg> YouTube</a>
        </div>
    </footer>
</body>
</html>